/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"

/*=======External Functions This Runner Calls=====*/
extern void test_map_to_pos(void);
extern void test_put_n_bits32(void);
extern void test_rice_encoder(void);
extern void test_golomb_encoder(void);
extern void test_encode_value_zero(void);
extern void test_encode_value_multi(void);
extern void test_encode_value(void);
extern void test_compress_imagette_diff(void);
extern void test_compress_imagette_model(void);
extern void test_compress_imagette_raw(void);
extern void test_compress_imagette_error_cases(void);
extern void test_pad_bitstream(void);
extern void test_compress_data_internal_error_cases(void);
extern void test_compress_chunk_raw_singel_col(void);
extern void test_compress_chunk_raw_two_col(void);
extern void test_compress_chunk_aux(void);
extern void test_collection_zero_data_length(void);
extern void test_compress_chunk_error_cases(void);
extern void test_zero_escape_mech_is_used(void);
extern void test_COMPRESS_CHUNK_BOUND(void);
extern void test_compress_chunk_cmp_size_bound(void);
extern void test_compress_chunk_set_model_id_and_counter(void);
extern void test_support_function_call_NULL(void);
extern void test_missing_cmp_cfg_fx_cob_get_need_pars(void);
extern void test_print_cmp_info(void);
extern void test_buffer_overlaps(void);
extern void test_cmp_get_error_string(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("../test/cmp_icu/test_cmp_icu.c");
  run_test(test_map_to_pos, "test_map_to_pos", 73);
  run_test(test_put_n_bits32, "test_put_n_bits32", 177);
  run_test(test_rice_encoder, "test_rice_encoder", 583);
  run_test(test_golomb_encoder, "test_golomb_encoder", 652);
  run_test(test_encode_value_zero, "test_encode_value_zero", 796);
  run_test(test_encode_value_multi, "test_encode_value_multi", 920);
  run_test(test_encode_value, "test_encode_value", 1036);
  run_test(test_compress_imagette_diff, "test_compress_imagette_diff", 1149);
  run_test(test_compress_imagette_model, "test_compress_imagette_model", 1257);
  run_test(test_compress_imagette_raw, "test_compress_imagette_raw", 1311);
  run_test(test_compress_imagette_error_cases, "test_compress_imagette_error_cases", 1384);
  run_test(test_pad_bitstream, "test_pad_bitstream", 1502);
  run_test(test_compress_data_internal_error_cases, "test_compress_data_internal_error_cases", 1575);
  run_test(test_compress_chunk_raw_singel_col, "test_compress_chunk_raw_singel_col", 1636);
  run_test(test_compress_chunk_raw_two_col, "test_compress_chunk_raw_two_col", 1706);
  run_test(test_compress_chunk_aux, "test_compress_chunk_aux", 1827);
  run_test(test_collection_zero_data_length, "test_collection_zero_data_length", 1918);
  run_test(test_compress_chunk_error_cases, "test_compress_chunk_error_cases", 1987);
  run_test(test_zero_escape_mech_is_used, "test_zero_escape_mech_is_used", 2229);
  run_test(test_COMPRESS_CHUNK_BOUND, "test_COMPRESS_CHUNK_BOUND", 2250);
  run_test(test_compress_chunk_cmp_size_bound, "test_compress_chunk_cmp_size_bound", 2363);
  run_test(test_compress_chunk_set_model_id_and_counter, "test_compress_chunk_set_model_id_and_counter", 2453);
  run_test(test_support_function_call_NULL, "test_support_function_call_NULL", 2495);
  run_test(test_missing_cmp_cfg_fx_cob_get_need_pars, "test_missing_cmp_cfg_fx_cob_get_need_pars", 2523);
  run_test(test_print_cmp_info, "test_print_cmp_info", 2543);
  run_test(test_buffer_overlaps, "test_buffer_overlaps", 2569);
  run_test(test_cmp_get_error_string, "test_cmp_get_error_string", 2599);

  return UnityEnd();
}
