/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmp_icu.h"
#include <stdlib.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_cmp_cfg_icu_create(void);
extern void test_cmp_cfg_icu_buffers(void);
extern void test_cmp_cfg_icu_imagette(void);
extern void test_cmp_cfg_fx_cob(void);
extern void test_cmp_cfg_aux(void);
extern void test_map_to_pos(void);
extern void test_put_n_bits32(void);
extern void test_rice_encoder(void);
extern void test_golomb_encoder(void);
extern void test_encode_value_zero(void);
extern void test_encode_value_multi(void);
extern void test_encode_value(void);
extern void test_configure_encoder_setup(void);
extern void test_compress_imagette_diff(void);
extern void test_compress_imagette_model(void);
extern void test_compress_imagette_stuff(void);
extern void test_compress_imagette_raw(void);
extern void test_compress_imagette_error_cases(void);
extern void test_compress_multi_entry_hdr(void);
extern void test_compress_s_fx_raw(void);
extern void test_compress_s_fx_staff(void);
extern void test_compress_s_fx_model_multi(void);
extern void test_compress_s_fx_error_cases(void);
extern void test_compress_s_fx_efx_error_cases(void);
extern void test_compress_s_fx_ncob_error_cases(void);
extern void test_compress_s_fx_efx_ncob_ecob_error_cases(void);
extern void test_compress_f_fx_error_cases(void);
extern void test_compress_f_fx_efx_error_cases(void);
extern void test_compress_f_fx_ncob_error_cases(void);
extern void test_compress_f_fx_efx_ncob_ecob(void);
extern void test_compress_l_fx_error_cases(void);
extern void test_compress_l_fx_efx_error_cases(void);
extern void test_compress_l_fx_ncob_error_cases(void);
extern void test_compress_l_fx_efx_ncob_ecob_error_cases(void);
extern void test_compress_nc_offset_error_cases(void);
extern void test_compress_nc_background_error_cases(void);
extern void test_compress_smearing_error_cases(void);
extern void test_pad_bitstream(void);
extern void test_cmp_data_to_big_endian_error_cases(void);
extern void test_icu_compress_data_error_cases(void);
extern void test_zero_escape_mech_is_used(void);
extern void test_support_function_call_NULL(void);
extern void test_print_cmp_info(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("../test/cmp_icu/test_cmp_icu.c");
  run_test(test_cmp_cfg_icu_create, "test_cmp_cfg_icu_create", 63);
  run_test(test_cmp_cfg_icu_buffers, "test_cmp_cfg_icu_buffers", 186);
  run_test(test_cmp_cfg_icu_imagette, "test_cmp_cfg_icu_imagette", 448);
  run_test(test_cmp_cfg_fx_cob, "test_cmp_cfg_fx_cob", 576);
  run_test(test_cmp_cfg_aux, "test_cmp_cfg_aux", 1035);
  run_test(test_map_to_pos, "test_map_to_pos", 1173);
  run_test(test_put_n_bits32, "test_put_n_bits32", 1277);
  run_test(test_rice_encoder, "test_rice_encoder", 1676);
  run_test(test_golomb_encoder, "test_golomb_encoder", 1745);
  run_test(test_encode_value_zero, "test_encode_value_zero", 1848);
  run_test(test_encode_value_multi, "test_encode_value_multi", 1970);
  run_test(test_encode_value, "test_encode_value", 2062);
  run_test(test_configure_encoder_setup, "test_configure_encoder_setup", 2175);
  run_test(test_compress_imagette_diff, "test_compress_imagette_diff", 2363);
  run_test(test_compress_imagette_model, "test_compress_imagette_model", 2396);
  run_test(test_compress_imagette_stuff, "test_compress_imagette_stuff", 2444);
  run_test(test_compress_imagette_raw, "test_compress_imagette_raw", 2480);
  run_test(test_compress_imagette_error_cases, "test_compress_imagette_error_cases", 2546);
  run_test(test_compress_multi_entry_hdr, "test_compress_multi_entry_hdr", 2631);
  run_test(test_compress_s_fx_raw, "test_compress_s_fx_raw", 2710);
  run_test(test_compress_s_fx_staff, "test_compress_s_fx_staff", 2763);
  run_test(test_compress_s_fx_model_multi, "test_compress_s_fx_model_multi", 2816);
  run_test(test_compress_s_fx_error_cases, "test_compress_s_fx_error_cases", 3039);
  run_test(test_compress_s_fx_efx_error_cases, "test_compress_s_fx_efx_error_cases", 3100);
  run_test(test_compress_s_fx_ncob_error_cases, "test_compress_s_fx_ncob_error_cases", 3175);
  run_test(test_compress_s_fx_efx_ncob_ecob_error_cases, "test_compress_s_fx_efx_ncob_ecob_error_cases", 3256);
  run_test(test_compress_f_fx_error_cases, "test_compress_f_fx_error_cases", 3372);
  run_test(test_compress_f_fx_efx_error_cases, "test_compress_f_fx_efx_error_cases", 3413);
  run_test(test_compress_f_fx_ncob_error_cases, "test_compress_f_fx_ncob_error_cases", 3474);
  run_test(test_compress_f_fx_efx_ncob_ecob, "test_compress_f_fx_efx_ncob_ecob", 3538);
  run_test(test_compress_l_fx_error_cases, "test_compress_l_fx_error_cases", 3634);
  run_test(test_compress_l_fx_efx_error_cases, "test_compress_l_fx_efx_error_cases", 3708);
  run_test(test_compress_l_fx_ncob_error_cases, "test_compress_l_fx_ncob_error_cases", 3795);
  run_test(test_compress_l_fx_efx_ncob_ecob_error_cases, "test_compress_l_fx_efx_ncob_ecob_error_cases", 3904);
  run_test(test_compress_nc_offset_error_cases, "test_compress_nc_offset_error_cases", 4046);
  run_test(test_compress_nc_background_error_cases, "test_compress_nc_background_error_cases", 4104);
  run_test(test_compress_smearing_error_cases, "test_compress_smearing_error_cases", 4176);
  run_test(test_pad_bitstream, "test_pad_bitstream", 4248);
  run_test(test_cmp_data_to_big_endian_error_cases, "test_cmp_data_to_big_endian_error_cases", 4321);
  run_test(test_icu_compress_data_error_cases, "test_icu_compress_data_error_cases", 4379);
  run_test(test_zero_escape_mech_is_used, "test_zero_escape_mech_is_used", 4399);
  run_test(test_support_function_call_NULL, "test_support_function_call_NULL", 4414);
  run_test(test_print_cmp_info, "test_print_cmp_info", 4430);

  return UnityEnd();
}
