/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"

/*=======External Functions This Runner Calls=====*/
extern void test_random_round_trip_like_rdcu_compression(void);
extern void test_random_compression_decompress_rdcu_data(void);
extern void test_random_collection_round_trip(void);
extern void test_cmp_collection_raw(void);
extern void test_cmp_collection_diff(void);
extern void test_cmp_collection_worst_case(void);
extern void test_cmp_collection_imagette_worst_case(void);
extern void test_cmp_decmp_chunk_raw(void);
extern void test_cmp_decmp_chunk_worst_case(void);
extern void test_cmp_decmp_diff(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("../test/cmp_decmp/test_cmp_decmp.c");
  run_test(test_random_round_trip_like_rdcu_compression, "test_random_round_trip_like_rdcu_compression", 808);
  run_test(test_random_compression_decompress_rdcu_data, "test_random_compression_decompress_rdcu_data", 893);
  run_test(test_random_collection_round_trip, "test_random_collection_round_trip", 944);
  run_test(test_cmp_collection_raw, "test_cmp_collection_raw", 1063);
  run_test(test_cmp_collection_diff, "test_cmp_collection_diff", 1133);
  run_test(test_cmp_collection_worst_case, "test_cmp_collection_worst_case", 1217);
  run_test(test_cmp_collection_imagette_worst_case, "test_cmp_collection_imagette_worst_case", 1304);
  run_test(test_cmp_decmp_chunk_raw, "test_cmp_decmp_chunk_raw", 1390);
  run_test(test_cmp_decmp_chunk_worst_case, "test_cmp_decmp_chunk_worst_case", 1491);
  run_test(test_cmp_decmp_diff, "test_cmp_decmp_diff", 1602);

  return UnityEnd();
}
