/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <stdint.h>
#include <cmp_rdcu.h>
#include <rdcu_cmd.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_rdcu_cfg_create(void);
extern void test_rdcu_cfg_buffers_raw_diff(void);
extern void test_rdcu_cfg_buffers_model(void);
extern void test_rdcu_cfg_imagette(void);
extern void test_rdcu_cmp_cfg_is_invalid(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("../test/cmp_rdcu/test_cmp_rdcu_cfg.c");
  run_test(test_rdcu_cfg_create, "test_rdcu_cfg_create", 30);
  run_test(test_rdcu_cfg_buffers_raw_diff, "test_rdcu_cfg_buffers_raw_diff", 143);
  run_test(test_rdcu_cfg_buffers_model, "test_rdcu_cfg_buffers_model", 272);
  run_test(test_rdcu_cfg_imagette, "test_rdcu_cfg_imagette", 426);
  run_test(test_rdcu_cmp_cfg_is_invalid, "test_rdcu_cmp_cfg_is_invalid", 644);

  return UnityEnd();
}
