/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"

/*=======External Functions This Runner Calls=====*/
extern void test_cmp_col_get_subservice(void);
extern void test_cmp_col_get_and_set(void);
extern void test_convert_subservice_functions(void);
extern void test_size_of_a_sample(void);
extern void test_cmp_input_big_to_cpu_endianness(void);
extern void test_be_to_cpu_chunk(void);
extern void test_be_to_cpu_chunk_error_cases(void);
extern void test_cmp_input_big_to_cpu_endianness_error_cases(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("../test/cmp_data_types/test_cmp_data_types.c");
  run_test(test_cmp_col_get_subservice, "test_cmp_col_get_subservice", 32);
  run_test(test_cmp_col_get_and_set, "test_cmp_col_get_and_set", 44);
  run_test(test_convert_subservice_functions, "test_convert_subservice_functions", 155);
  run_test(test_size_of_a_sample, "test_size_of_a_sample", 173);
  run_test(test_cmp_input_big_to_cpu_endianness, "test_cmp_input_big_to_cpu_endianness", 237);
  run_test(test_be_to_cpu_chunk, "test_be_to_cpu_chunk", 283);
  run_test(test_be_to_cpu_chunk_error_cases, "test_be_to_cpu_chunk_error_cases", 620);
  run_test(test_cmp_input_big_to_cpu_endianness_error_cases, "test_cmp_input_big_to_cpu_endianness_error_cases", 675);

  return UnityEnd();
}
