/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "compiler.h"
#include "cmp_entity.h"
#include <string.h>
#include <stdlib.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_count_leading_ones(void);
extern void test_rice_decoder(void);
extern void test_golomb_decoder(void);
extern void test_select_decoder(void);
extern void test_get_n_bits32(void);
extern void test_decode_normal(void);
extern void test_decode_zero(void);
extern void test_decode_multi(void);
extern void test_re_map_to_pos(void);
extern void test_cmp_decmp_n_imagette_raw(void);
extern void test_decompress_imagette_model(void);
extern void test_cmp_decmp_s_fx_diff(void);
extern void test_s_fx_diff(void);
extern void test_s_fx_model(void);
extern void test_cmp_ent_write_cmp_pars(void);
extern void test_cmp_ent_read_header_error_cases(void);
extern void test_decompression_error_cases(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("../test/cmp_icu/test_decmp.c");
  run_test(test_count_leading_ones, "test_count_leading_ones", 37);
  run_test(test_rice_decoder, "test_rice_decoder", 80);
  run_test(test_golomb_decoder, "test_golomb_decoder", 197);
  run_test(test_select_decoder, "test_select_decoder", 385);
  run_test(test_get_n_bits32, "test_get_n_bits32", 419);
  run_test(test_decode_normal, "test_decode_normal", 631);
  run_test(test_decode_zero, "test_decode_zero", 690);
  run_test(test_decode_multi, "test_decode_multi", 727);
  run_test(test_re_map_to_pos, "test_re_map_to_pos", 831);
  run_test(test_cmp_decmp_n_imagette_raw, "test_cmp_decmp_n_imagette_raw", 930);
  run_test(test_decompress_imagette_model, "test_decompress_imagette_model", 977);
  run_test(test_cmp_decmp_s_fx_diff, "test_cmp_decmp_s_fx_diff", 1018);
  run_test(test_s_fx_diff, "test_s_fx_diff", 1088);
  run_test(test_s_fx_model, "test_s_fx_model", 1128);
  run_test(test_cmp_ent_write_cmp_pars, "test_cmp_ent_write_cmp_pars", 1204);
  run_test(test_cmp_ent_read_header_error_cases, "test_cmp_ent_read_header_error_cases", 1741);
  run_test(test_decompression_error_cases, "test_decompression_error_cases", 1805);

  return UnityEnd();
}
