/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"

/*=======External Functions This Runner Calls=====*/
extern void test_bitstream(void);
extern void test_unary_decoder(void);
extern void test_rice_decoder(void);
extern void test_golomb_decoder(void);
extern void test_select_decoder(void);
extern void test_decode_zero(void);
extern void test_zero_refill_needed(void);
extern void test_decode_multi(void);
extern void test_multi_refill_needed(void);
extern void test_re_map_to_pos(void);
extern void test_cmp_decmp_rdcu_raw(void);
extern void test_decompress_imagette_model(void);
extern void test_decompress_imagette_chunk_raw(void);
extern void test_decompression_error_cases(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("../test/decmp/test_decmp.c");
  run_test(test_bitstream, "test_bitstream", 41);
  run_test(test_unary_decoder, "test_unary_decoder", 130);
  run_test(test_rice_decoder, "test_rice_decoder", 228);
  run_test(test_golomb_decoder, "test_golomb_decoder", 395);
  run_test(test_select_decoder, "test_select_decoder", 617);
  run_test(test_decode_zero, "test_decode_zero", 651);
  run_test(test_zero_refill_needed, "test_zero_refill_needed", 723);
  run_test(test_decode_multi, "test_decode_multi", 751);
  run_test(test_multi_refill_needed, "test_multi_refill_needed", 855);
  run_test(test_re_map_to_pos, "test_re_map_to_pos", 901);
  run_test(test_cmp_decmp_rdcu_raw, "test_cmp_decmp_rdcu_raw", 953);
  run_test(test_decompress_imagette_model, "test_decompress_imagette_model", 1010);
  run_test(test_decompress_imagette_chunk_raw, "test_decompress_imagette_chunk_raw", 1056);
  run_test(test_decompression_error_cases, "test_decompression_error_cases", 1102);

  return UnityEnd();
}
